# Blog settings
permalink: /blog/:title

collections:
  notes:
    output: true
    permalink: /notes/:title

# My variables
name: Charlie Drage
title: Charlie Drage | Freelance Software Developer
description: Hey, I'm Charlie! A freelance software developer in Canada. I'm addicted to Linux, I love coding and I have a fascination with flight / drones.
google_verification: null
tldr: Programmer, minimalistic, Linux fanatic, drone-flying enthusiast. I blog a lot of TLDR's.



# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
